name: Update documentation on pull request

on:
  # Runs on pushes targeting the default branch
  pull_request:
        types: [closed]
        branches: ["main"]

jobs:
 update-docs:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
        - name: Install OpenAI Python package
          run: pip install azure-ai-generative

        - name: Call LLM
          env:
            AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
            AZURE_OPENAI_KEY: ${{ secrets.AZURE_OPENAI_KEY }}
            AZURE_OPENAI_DEPLOYMENT: ${{ secrets.AZURE_OPENAI_DEPLOYMENT }}
          run: python .github/workflows/scripts/call_llm.py
    

