name: Update documentation on pull request

on:
  # Runs on pushes targeting the default branch
  pull_request:
        types: [closed]
        branches: ["main"]
  workflow_dispatch:

jobs:
 update-docs:
    if: (github.event_name == 'workflow_dispatch') || (github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:
        - name: Check-out devops repository
          uses: actions/checkout@v2

        - name: Get changed files
          id: changed-files
          uses: tj-actions/changed-files@v14.6

        - name: List all changed files
          run: |
            for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
              echo "$file was changed"
            done

          # TODO: pass this to the LLM

        - name: Install OpenAI Python package
          run: pip install openai

        - name: Call LLM and update documentation
          env:
            AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
            AZURE_OPENAI_KEY: ${{ secrets.AZURE_OPENAI_KEY }}
            AZURE_OPENAI_DEPLOYMENT: ${{ secrets.AZURE_OPENAI_DEPLOYMENT }}
          run: python .github/workflows/scripts/call_llm.py
    
        - name: Set up Git
          run: |
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"

        - name: Create branch, commit, and push
          run: |
            branch="update-docs-$(date +'%Y%m%d%H%M%S')"
            echo "branch=$branch" >> $GITHUB_ENV
            git checkout -b $branch
            git add docs/documentation.md
            git commit -m "Update documentation with LLM"
            git push origin $branch

        - name: Create Pull Request
          uses: peter-evans/create-pull-request@v6
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            branch: ${{ env.branch }}
            title: "Update documentation with LLM"
            body: "This PR updates the documentation using the latest LLM output."
            base: main
